### ISSUE TITLE
Error Compiling alarm3f.c

### ISSUE THREAD

**Issue by kwryankrattiger** [ROCm-Developer-Tools/flang#61]
This currently does not build with the latest llvm-amdgpu provided clang

`runtime/flang/alarm3f.c`

```c
extern int alarm();
```

should be

```c
extern int alarm(int);
```

ref.
https://www.man7.org/linux/man-pages/man2/alarm.2.html

@estewart08 @srekolam

**Comment by ronlieb** [comment]
i think you are looking at the master  branch 
https://github.com/ROCm-Developer-Tools/flang/blob/master/runtime/flang/alarm3f.c

whereas aomp uses branch aomp-dev
https://github.com/ROCm-Developer-Tools/flang/blob/aomp-dev/runtime/flang/alarm3f.c

we maintain the aomp-dev branch, the master branch is more a less a reference from 1+ years ago

**Comment by kwryankrattiger** [comment]
I am having this issue based on the 5.1.x released tarball.

https://github.com/ROCm-Developer-Tools/flang/blob/rocm-5.1.x/runtime/flang/alarm3f.c

**Comment by ronlieb** [comment]
please try the 5.2.1 source 
https://github.com/ROCm-Developer-Tools/aomp/archive/refs/tags/rocm-5.2.1.tar.gz

or 15.0-3 source
https://github.com/ROCm-Developer-Tools/aomp/releases/download/rel_15.0-3/aomp-15.0-3.tar.gz

issues is fixed with

commit 57ac6f3d7e8fe68d642d7436bef45404d5b08aae
Author: estewart08 <ethan.stewart@amd.com>
Date:   Tue Mar 15 20:49:05 2022 -0500

    Fix conflicting types for alarm issue on centos-9 build. (#45)

**Comment by kwryankrattiger** [comment]
Sounds good, since it got fixed I will close this. I still need to make the older versions build so I will just cut a patch from that commit. Thanks!
